"""Markdown rendering for SpineScoutX finding graphs.

The rendered report is explicitly research-only: it opens with a prominent
non-diagnostic disclaimer and closes with a no-medical-advice footer. The body
summarises study provenance, lists findings level-by-level, links any evidence
figures, and reproduces the standard research limitations. No clinical,
diagnostic, or treatment language is produced.
"""

from __future__ import annotations

from pathlib import Path

from ..utils.paths import ensure_dir
from .finding_graph import Finding, FindingGraph

TOP_DISCLAIMER: str = "Research-only — not diagnostic — not for medical decision-making"
FOOTER_DISCLAIMER: str = (
    "No medical advice / no treatment recommendation. This report is generated by a "
    "research prototype for methods development only."
)

_TABLE_HEADER: tuple[str, ...] = (
    "Level",
    "Condition",
    "Side",
    "Grade",
    "Confidence",
    "Calibrated",
    "Flag",
    "AEC",
    "Region",
    "Region source",
)


def _fmt_float(value: float) -> str:
    """Format a probability-like float to three decimals."""
    return f"{value:.3f}"


def _fmt_optional_float(value: float | None) -> str:
    """Format an optional float, using a dash when absent."""
    return "—" if value is None else _fmt_float(value)


def _fmt_optional_str(value: str | None) -> str:
    """Format an optional string, using a dash when absent."""
    return "—" if value in (None, "") else str(value)


def _finding_row(finding: Finding) -> str:
    """Render a single finding as a Markdown table row."""
    cells = (
        finding.level,
        finding.condition,
        _fmt_optional_str(finding.side),
        finding.grade,
        _fmt_float(finding.confidence),
        _fmt_float(finding.calibrated_confidence),
        finding.uncertainty_flag,
        _fmt_optional_float(finding.evidence_consistency),
        finding.evidence_region,
        finding.evidence_region_source,
    )
    return "| " + " | ".join(cells) + " |"


def _findings_table(findings: list[Finding]) -> list[str]:
    """Render the level-wise findings table (header + rows)."""
    lines = [
        "| " + " | ".join(_TABLE_HEADER) + " |",
        "| " + " | ".join("---" for _ in _TABLE_HEADER) + " |",
    ]
    if not findings:
        return [*lines, "| _(no findings)_ |" + " |" * (len(_TABLE_HEADER) - 1)]
    ordered = sorted(findings, key=lambda f: (f.level, f.condition, f.side or ""))
    lines.extend(_finding_row(finding) for finding in ordered)
    return lines


def _evidence_links(findings: list[Finding], figure_paths: list[str] | None) -> list[str]:
    """Render evidence image links for findings plus any extra figures."""
    lines: list[str] = ["## Evidence images", ""]
    found_any = False
    for finding in findings:
        if finding.evidence_image_path:
            label = f"{finding.level} · {finding.condition}"
            lines.append(f"- {label}: ![{label}]({finding.evidence_image_path})")
            found_any = True
    for path in figure_paths or []:
        name = Path(path).name
        lines.append(f"- {name}: ![{name}]({path})")
        found_any = True
    if not found_any:
        lines.append("_(no evidence images attached)_")
    return lines


def render_markdown_report(
    graph: FindingGraph,
    figure_paths: list[str] | None = None,
) -> str:
    """Render a :class:`FindingGraph` as a research-only Markdown report string."""
    lines: list[str] = []

    lines.append(f"> **{TOP_DISCLAIMER}**")
    lines.append("")
    lines.append("# SpineScoutX Research Finding Report")
    lines.append("")

    lines.append("## Study summary")
    lines.append("")
    lines.append(f"- Study ID: `{graph.study_id}`")
    lines.append(f"- Dataset source: {graph.dataset_source}")
    lines.append(f"- Model version: {graph.model_version}")
    lines.append(f"- Run ID: `{graph.run_id}`")
    lines.append(f"- Research only: {graph.research_only}")
    lines.append(f"- Not diagnostic: {graph.not_diagnostic}")
    lines.append(f"- Number of findings: {len(graph.findings)}")
    lines.append("")

    lines.append("## Level-wise findings")
    lines.append("")
    lines.extend(_findings_table(graph.findings))
    lines.append("")

    lines.extend(_evidence_links(graph.findings, figure_paths))
    lines.append("")

    lines.append("## Limitations")
    lines.append("")
    if graph.limitations:
        lines.extend(f"- {item}" for item in graph.limitations)
    else:
        lines.append("_(none listed)_")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"_{FOOTER_DISCLAIMER}_")
    lines.append("")

    return "\n".join(lines)


def write_markdown_report(
    graph: FindingGraph,
    path: str | Path,
    figure_paths: list[str] | None = None,
) -> Path:
    """Render and write a Markdown report file; return the path."""
    out_path = Path(path)
    ensure_dir(out_path.parent)
    out_path.write_text(render_markdown_report(graph, figure_paths), encoding="utf-8")
    return out_path


__all__ = [
    "FOOTER_DISCLAIMER",
    "TOP_DISCLAIMER",
    "render_markdown_report",
    "write_markdown_report",
]
